/**
 * pages/SettingsPage.jsx
 * -----------------------
 * About & Settings page.
 *
 * Contains the mandatory AI companion disclosure notice —
 * placed here so it's accessible but does NOT break chat immersion.
 * This follows standard industry practice for AI companion applications.
 */

import React from 'react';
import { useNavigate } from 'react-router-dom';

export default function SettingsPage() {
  const navigate = useNavigate();

  return (
    <div className="page settings-page">
      <div className="bg-glow bg-glow--top-left" aria-hidden="true" />

      {/* Top bar */}
      <header className="topbar" role="banner">
        <div className="topbar__brand">
          <span className="topbar__logo gradient-text">✦ Spark</span>
        </div>
        <button
          className="topbar__back-btn"
          onClick={() => navigate(-1)}
          aria-label="Go back"
          id="settings-back-btn"
        >
          ← Back
        </button>
      </header>

      <main className="settings-main container" id="settings-main">
        <div className="settings-content">

          {/* Page title */}
          <h1 className="settings-title">About <span className="gradient-text">Spark</span></h1>
          <p className="settings-subtitle">
            Your AI companion platform — honest, thoughtful, always available.
          </p>

          {/* ============================================================
              AI COMPANION DISCLOSURE — REQUIRED / INDUSTRY STANDARD
              Non-intrusive: lives in About/Settings, not in the chat UI.
              ============================================================ */}
          <section
            className="settings-card settings-card--disclosure"
            aria-labelledby="ai-disclosure-heading"
            id="ai-disclosure"
          >
            <div className="settings-card__icon" aria-hidden="true">🤖</div>
            <div className="settings-card__body">
              <h2 id="ai-disclosure-heading" className="settings-card__title">
                AI Companion Disclosure
              </h2>
              <p className="settings-card__text">
                <strong>Spark is an AI-powered companion platform.</strong> All personas
                you interact with — including Luna, Ethan, Zara, and any others — are
                artificial intelligence characters. They are not real people.
              </p>
              <p className="settings-card__text">
                Conversations are generated by large language models and are designed
                to feel natural and engaging. While the AI adapts to your messages and
                remembers context from your conversations, it does not have genuine
                feelings, experiences, or a life outside of these chats.
              </p>
              <p className="settings-card__text">
                We believe in transparency: Spark is entertainment and companionship
                technology — a space for meaningful, enjoyable conversations — and we
                want you to engage with that understanding.
              </p>
            </div>
          </section>

          {/* Platform info */}
          <section className="settings-card" aria-labelledby="about-platform-heading">
            <div className="settings-card__icon" aria-hidden="true">✦</div>
            <div className="settings-card__body">
              <h2 id="about-platform-heading" className="settings-card__title">
                About the Platform
              </h2>
              <p className="settings-card__text">
                Spark uses state-of-the-art language models to power deeply personalized
                conversations. Each AI companion has a unique backstory, personality, tone,
                and conversational style — crafted to feel distinctive and authentic.
              </p>
              <p className="settings-card__text">
                The platform features long-term memory so companions remember what you've
                shared across conversations, making each interaction feel more personal
                over time.
              </p>
            </div>
          </section>

          {/* Privacy / data */}
          <section className="settings-card" aria-labelledby="privacy-heading">
            <div className="settings-card__icon" aria-hidden="true">🔒</div>
            <div className="settings-card__body">
              <h2 id="privacy-heading" className="settings-card__title">
                Your Conversations
              </h2>
              <p className="settings-card__text">
                Chat history is stored locally to enable memory and context continuity.
                Your session is identified by an anonymous ID stored in your browser.
                No account creation is required.
              </p>
            </div>
          </section>

          {/* Version info */}
          <div className="settings-footer">
            <p>Spark AI Companion Platform · v1.0.0</p>
            <p>Built with FastAPI · React · Groq · Anthropic Claude · ChromaDB</p>
          </div>

        </div>
      </main>
    </div>
  );
}
